update for issue #8
MeiyappanKannappa/shalo pull request #9
Opened 2024-10-05 10:38 UTC by Sagar2006

1. **Flag Handling**: The code introduces a new command `add-folder` which can be used to add a folder to the sparse checkout. This command is separate from the `add` command, which now includes logic to handle dependencies.

2. **`add` Command**: The `add` command is designed to add an app to the monorepo. If the `--folder-only` flag is not used, it computes the graph from the existing `output.json` and checks out additional dependencies for the app.

3. **`addApp` Function**: This function checks if the `--folder-only` flag is set. If it is, it adds only the specified folder. If not, it retrieves the dependencies for the app using the `getAppDependencies` function and adds them to the sparse checkout.

2024-10-05 13:05 UTC, MeiyappanKannappa requested changes
If you have tried in with some sample mono repo, can you please attach screenshot if possible?

2024-10-05 13:05 UTC, MeiyappanKannappa commented on src/index.ts
> +                executeCommand(`git sparse-checkout add ${dep.path}`);
Can you please add error handling and notify in the console, if the folder cannot be added or the folder name is not right?

2024-10-05 13:05 UTC, MeiyappanKannappa commented on Readme.md
> +shalo add <FOLDER_NAME>
Please add the flag -f, in the example. So user can understand it better

2024-10-05 13:05 UTC, MeiyappanKannappa commented on src/index.ts
> +        if (dependencies) {
Can we pls add null check, and handle it appropriately

2024-10-05 13:28 UTC, Sagar2006 commented
> If you have tried in with some sample mono repo, can you please attach screenshot if possible?

do you want to test any specific command?

2024-10-05 13:36 UTC, Kamalesh-Seervi commented
> > If you have tried in with some sample mono repo, can you please attach screenshot if possible?
> 
> do you want to test any specific command?

https://github.com/nrwl/nx-examples
try this example project with you code and test it

2024-10-05 14:05 UTC, Sagar2006 commented
kindly check i have done some changes check the commit number 3 
here are some screenshots
![Untitled14](https://github.com/user-attachments/assets/f3889374-b63f-4e43-ae55-cb3778129d3c)
![Untitled13](https://github.com/user-attachments/assets/e7457e6f-ae87-478e-96ce-e74c5d78f080)
![Untitled12](https://github.com/user-attachments/assets/909ffcd5-4cd3-462f-ad42-e909f7773570)
![Untitled11](https://github.com/user-attachments/assets/ea326a4c-2319-4207-987d-a9d254ec7517)
Please do let me know if i can contribute more to this project

2024-10-05 14:32 UTC, MeiyappanKannappa commented
> > If you have tried in with some sample mono repo, can you please attach screenshot if possible?
> 
> do you want to test any specific command?

Can we add screenshots for the commad and with -f flag

2024-10-06 08:01 UTC, Sagar2006 commented
![image](https://github.com/user-attachments/assets/ae0d9f4e-e45f-4b7e-965e-a723355fb605)
![image](https://github.com/user-attachments/assets/542bee1b-cebd-4738-ac69-8d81742ba33b)
tried a lot but unable to run add command with -f flag. Only add command is running but -f is not working

2024-10-06 08:20 UTC, Kamalesh-Seervi commented
I have done both 6 and 8 issue and those are sorted

2024-10-06 08:46 UTC, Kamalesh-Seervi commented
thank you trying to solve this issue 
that issue is sorted with recent pr

2024-10-06 08:46 UTC, closed without merging